/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author gtaan
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNuevoElemento = new javax.swing.JButton();
        jPanelMuestreo = new javax.swing.JPanel();
        jButtonActualizacionElemento = new javax.swing.JButton();
        jButtonBajaElemento = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemGestionMonitores = new javax.swing.JMenuItem();
        jMenuItemCuotaMonitor = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMenuItemGestionSocios = new javax.swing.JMenuItem();
        jMenuItemBuscarSocio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSociosActividad = new javax.swing.JMenuItem();
        jMenuItemAltaBajaSocioActividad = new javax.swing.JMenuItem();
        jMenuItemCuotaActividad = new javax.swing.JMenuItem();
        JMenuSalir = new javax.swing.JMenu();
        ButtonCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión del Gimnasio \"Body Perfect\"");
        setLocation(new java.awt.Point(250, 200));

        jButtonNuevoElemento.setText("Nuevo Monitor");
        jButtonNuevoElemento.setActionCommand("NuevoElemento");

        jPanelMuestreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanelMuestreoLayout = new javax.swing.GroupLayout(jPanelMuestreo);
        jPanelMuestreo.setLayout(jPanelMuestreoLayout);
        jPanelMuestreoLayout.setHorizontalGroup(
            jPanelMuestreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelMuestreoLayout.setVerticalGroup(
            jPanelMuestreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jButtonActualizacionElemento.setText("Actualización de Monitor");
        jButtonActualizacionElemento.setActionCommand("ActualizacionElemento");

        jButtonBajaElemento.setText("Baja de Monitor");
        jButtonBajaElemento.setActionCommand("BajaElemento");

        jMenu1.setText("Monitores");

        jMenuItemGestionMonitores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemGestionMonitores.setText("Gestión de Monitores");
        jMenuItemGestionMonitores.setActionCommand("GestionMonitores");
        jMenu1.add(jMenuItemGestionMonitores);

        jMenuItemCuotaMonitor.setText("Cuota de Monitor");
        jMenu1.add(jMenuItemCuotaMonitor);

        jMenuBar1.add(jMenu1);

        jMenuSocios.setText("Socios");

        jMenuItemGestionSocios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemGestionSocios.setText("Gestión de Socios");
        jMenuItemGestionSocios.setActionCommand("GestionSocios");
        jMenuSocios.add(jMenuItemGestionSocios);

        jMenuItemBuscarSocio.setText("Buscar Socio");
        jMenuSocios.add(jMenuItemBuscarSocio);

        jMenuBar1.add(jMenuSocios);

        jMenu3.setText("Actividades");

        jMenuItemSociosActividad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemSociosActividad.setText("Socios por Actividad");
        jMenu3.add(jMenuItemSociosActividad);

        jMenuItemAltaBajaSocioActividad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemAltaBajaSocioActividad.setText("Gestionar Alta/Baja de Socio en Actividad");
        jMenuItemAltaBajaSocioActividad.setActionCommand("AltaBajaSocioActividad");
        jMenu3.add(jMenuItemAltaBajaSocioActividad);

        jMenuItemCuotaActividad.setText("Cuota de Actividad");
        jMenu3.add(jMenuItemCuotaActividad);

        jMenuBar1.add(jMenu3);

        JMenuSalir.setText("Salir");

        ButtonCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        ButtonCerrar.setText("Salir de la Aplicación");
        ButtonCerrar.setActionCommand("Cerrar");
        JMenuSalir.add(ButtonCerrar);

        jMenuBar1.add(JMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonNuevoElemento)
                .addGap(18, 18, 18)
                .addComponent(jButtonActualizacionElemento)
                .addGap(18, 18, 18)
                .addComponent(jButtonBajaElemento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMuestreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMuestreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoElemento)
                    .addComponent(jButtonActualizacionElemento)
                    .addComponent(jButtonBajaElemento))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ButtonCerrar;
    public javax.swing.JMenu JMenuSalir;
    public javax.swing.JButton jButtonActualizacionElemento;
    public javax.swing.JButton jButtonBajaElemento;
    public javax.swing.JButton jButtonNuevoElemento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemAltaBajaSocioActividad;
    public javax.swing.JMenuItem jMenuItemBuscarSocio;
    public javax.swing.JMenuItem jMenuItemCuotaActividad;
    public javax.swing.JMenuItem jMenuItemCuotaMonitor;
    public javax.swing.JMenuItem jMenuItemGestionMonitores;
    public javax.swing.JMenuItem jMenuItemGestionSocios;
    public javax.swing.JMenuItem jMenuItemSociosActividad;
    private javax.swing.JMenu jMenuSocios;
    public javax.swing.JPanel jPanelMuestreo;
    // End of variables declaration//GEN-END:variables
}
